function Paddle(side){this.length=40;this.depth=7;this.offset=70;this.front=(side=='l')?-(width/2-this.offset-this.depth):width/2-this.offset-this.depth;this.back=(side=='l')?-(width/2-this.offset):width/2-this.offset;this.y=0;var accel=1.3;var deaccel=0.75;var terminal=9.5;this.velocity=0;this.points=0;this.upward;this.downward;this.listen=function(up1=38,down1=40,up2=87,down2=83){if(key[up1]||key[up2]){this.upward=!0}else{this.upward=!1}
if(key[down1]||key[down2]){this.downward=!0}else{this.downward=!1}}
this.think=function(follow_margin=25){if(ball.y>this.y&&Math.abs(ball.y-this.y)>=follow_margin){this.upward=!0;this.downward=!1}else if(ball.y<this.y&&Math.abs(ball.y-this.y)>=follow_margin){this.downward=!0;this.upward=!1}else{this.upward=!1;this.downward=!1}}
this.draw=function(){if(this.upward){this.velocity+=accel;if(this.velocity>terminal){this.velocity=terminal}}
if(this.downward){this.velocity-=accel;if(this.velocity<-terminal){this.velocity=-terminal}}else if(this.velocity!=0&&!(this.upward)){this.velocity*=deaccel;if(Math.abs(this.velocity)<0.02){this.velocity=0}}
this.y+=this.velocity;if(Math.abs(this.y)>height/2+this.length/2){this.y=-this.y}
if(side=='l'){bg.fillRect(this.offset,height/2-this.length/2-this.y,this.depth,this.length)}else if(side=='r'){bg.fillRect(width-this.offset,height/2-this.length/2-this.y,-this.depth,this.length)}}}
const ball={size:10,maxY:7.25,wait:!1,set:function(restart=!1){draw_ui();if(player.points<win&&cpu.points<win){this.x=0;this.y=0;this.velocityX=(restart)?[6.25,-6.25][Math.round(Math.random())]:this.velocityX;this.velocityY=(restart)?0:(Math.random()*2-1)}},update:function(){this.top=this.y+this.size/2;this.bottom=this.y-this.size/2;this.left=this.x-this.size/2;this.right=this.x+this.size/2;if(this.left<=player.front){let player_top=player.y+player.length/2;let player_bottom=player.y-player.length/2;if(this.right>=player.back&&this.bottom<=player_top&&this.top>=player_bottom){player_sound.play();this.velocityX=Math.abs(this.velocityX);this.velocityY=-((player.y-this.y)/(player.length/2))*this.maxY}else if(this.right<=-width/2){fail.play();cpu.points++;this.wait=!0
this.set()}}else if(this.right>=cpu.front){let cpu_top=cpu.y+cpu.length/2;let cpu_bottom=cpu.y-cpu.length/2;if(this.left<=cpu.back&&this.bottom<=cpu_top&&this.top>=cpu_bottom){cpu_sound.play();this.velocityX=-Math.abs(this.velocityX);this.velocityY=-((cpu.y-this.y)/(cpu.length/2))*this.maxY}else if(this.left>=width/2){success.play();player.points++;this.wait=true;this.set()}}
if(this.top>=height/2){this.velocityY=-Math.abs(this.velocityY);bounce.play()}else if(this.bottom<=-height/2){this.velocityY=Math.abs(this.velocityY);bounce.play()}
if(this.wait==!1){this.x+=this.velocityX;this.y+=this.velocityY}},draw:function(){bg.fillRect(width/2-this.size/2+this.x,height/2-this.size/2-this.y,this.size,this.size)}}
const fg=document.getElementById("front").getContext("2d");const bg=document.getElementById("back").getContext("2d",{alpha:!1});const width=725;const height=500;{let canvas=document.getElementById("back");fg.scale(canvas.width/width,canvas.height/height);bg.scale(canvas.width/width,canvas.height/height)}
fg.lineWidth=5;fg.setLineDash([5,15]);fg.font="75px pongscore";fg.textAlign="right";const player_sound=new Audio("sounds/focus.wav");const cpu_sound=new Audio("sounds/revenge.wav");const bounce=new Audio("sounds/routine.wav");const success=new Audio("sounds/provoke.wav");const fail=new Audio("sounds/resolve.wav");{let volume=.2;player_sound.volume=volume;cpu_sound.volume=volume;bounce.volume=volume;success.volume=volume;fail.volume=volume}
const frame_interval=1000/60;win=11;paused=!0;key=[];window.addEventListener("keydown",function(event){key[event.keyCode]=!0;player.listen();if(key[38]||key[40]){event.preventDefault()}
if(key[80]||key[27]){pause()}else if(key[82]){play()}});window.addEventListener("keyup",function(){key[event.keyCode]=undefined;player.listen()});player=new Paddle('l');cpu=new Paddle('r');font=new FontFace("pongscore","url(pongscore.otf)");font.load().then(()=>play());let then=-17;function refresh(now){if(player.points<win&&cpu.points<win){let elapsed=now-then;if(elapsed>=frame_interval){cpu.think(Math.random()*21+5);if(ball.wait){setTimeout(()=>ball.wait=!1,375)}else{ball.update()}
bg.clearRect(0,0,width,height);ball.draw();cpu.draw();player.draw();then=now-(elapsed%frame_interval)}
frame=requestAnimationFrame(refresh)}else pause()}
function draw_ui(){fg.clearRect(0,0,width,height);fg.beginPath();fg.moveTo(width/2,height);fg.lineTo(width/2,0);fg.stroke();fg.fillText(player.points,256,126);fg.fillText(cpu.points,618,126)}
function recolor(current){const colors=["#ffffff","#00be00","#e3b612"];let color=current;while(color==current){color=colors[Math.floor(Math.random()*colors.length)]}
return color}
function play(){fg.strokeStyle=fg.fillStyle=bg.fillStyle=recolor(bg.fillStyle);player.y=cpu.y=0;player.velocity=cpu.velocity=0;player.points=cpu.points=0;ball.wait=!1;ball.set(!0);if(paused)pause()}
function pause(){paused=!paused;if(paused){cancelAnimationFrame(frame)}else{frame=requestAnimationFrame(refresh)}}
